// Mocks generated by Mockito 5.4.6 from annotations
// in beacon_project/test/dashboard_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i9;

import 'package:beacon_project/models/device.dart' as _i3;
import 'package:beacon_project/repositories/cluster_member_repository.dart'
    as _i6;
import 'package:beacon_project/repositories/cluster_repository.dart' as _i5;
import 'package:beacon_project/repositories/device_repository.dart' as _i4;
import 'package:beacon_project/services/nearby_connections/nearby_connections.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nearby_connections/nearby_connections.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NearbyConnectionsInitiator].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearbyConnectionsInitiator extends _i1.Mock
    implements _i2.NearbyConnectionsInitiator {
  MockNearbyConnectionsInitiator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Device> get availableDevices =>
      (super.noSuchMethod(
            Invocation.getter(#availableDevices),
            returnValue: <_i3.Device>[],
          )
          as List<_i3.Device>);

  @override
  List<String> get connectedEndpoints =>
      (super.noSuchMethod(
            Invocation.getter(#connectedEndpoints),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, String> get activeConnections =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnections),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set deviceRepository(_i4.DeviceRepository? value) => super.noSuchMethod(
    Invocation.setter(#deviceRepository, value),
    returnValueForMissingStub: null,
  );

  @override
  set clusterRepository(_i5.ClusterRepository? value) => super.noSuchMethod(
    Invocation.setter(#clusterRepository, value),
    returnValueForMissingStub: null,
  );

  @override
  set clusterMemberRepository(_i6.ClusterMemberRepository? value) =>
      super.noSuchMethod(
        Invocation.setter(#clusterMemberRepository, value),
        returnValueForMissingStub: null,
      );

  @override
  set karim(dynamic value) => super.noSuchMethod(
    Invocation.setter(#karim, value),
    returnValueForMissingStub: null,
  );

  @override
  set deviceName(String? value) => super.noSuchMethod(
    Invocation.setter(#deviceName, value),
    returnValueForMissingStub: null,
  );

  @override
  set uuid(String? value) => super.noSuchMethod(
    Invocation.setter(#uuid, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> startCommunication() =>
      (super.noSuchMethod(
            Invocation.method(#startCommunication, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> inviteToCluster(String? endpointId, String? clusterId) =>
      (super.noSuchMethod(
            Invocation.method(#inviteToCluster, [endpointId, clusterId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> transferOwnershipBeforeDisconnect() =>
      (super.noSuchMethod(
            Invocation.method(#transferOwnershipBeforeDisconnect, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stopAll() =>
      (super.noSuchMethod(
            Invocation.method(#stopAll, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  dynamic init(
    _i4.DeviceRepository? deviceRepo,
    _i5.ClusterRepository? clusterRepo,
    _i6.ClusterMemberRepository? clusterMemberRepo,
  ) => super.noSuchMethod(
    Invocation.method(#init, [deviceRepo, clusterRepo, clusterMemberRepo]),
  );

  @override
  void onPayloadReceived(String? endpointId, _i8.Payload? payload) =>
      super.noSuchMethod(
        Invocation.method(#onPayloadReceived, [endpointId, payload]),
        returnValueForMissingStub: null,
      );

  @override
  dynamic sendMessage(
    String? endpointId,
    String? type,
    Map<String, dynamic>? data,
  ) => super.noSuchMethod(
    Invocation.method(#sendMessage, [endpointId, type, data]),
  );

  @override
  void onPayloadUpdate(String? endpointId, _i8.PayloadTransferUpdate? update) =>
      super.noSuchMethod(
        Invocation.method(#onPayloadUpdate, [endpointId, update]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NearbyConnectionsJoiner].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearbyConnectionsJoiner extends _i1.Mock
    implements _i2.NearbyConnectionsJoiner {
  MockNearbyConnectionsJoiner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> get discoveredClusters =>
      (super.noSuchMethod(
            Invocation.getter(#discoveredClusters),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  List<String> get connectedEndpoints =>
      (super.noSuchMethod(
            Invocation.getter(#connectedEndpoints),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, String> get activeConnections =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnections),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set deviceRepository(_i4.DeviceRepository? value) => super.noSuchMethod(
    Invocation.setter(#deviceRepository, value),
    returnValueForMissingStub: null,
  );

  @override
  set clusterRepository(_i5.ClusterRepository? value) => super.noSuchMethod(
    Invocation.setter(#clusterRepository, value),
    returnValueForMissingStub: null,
  );

  @override
  set clusterMemberRepository(_i6.ClusterMemberRepository? value) =>
      super.noSuchMethod(
        Invocation.setter(#clusterMemberRepository, value),
        returnValueForMissingStub: null,
      );

  @override
  set karim(dynamic value) => super.noSuchMethod(
    Invocation.setter(#karim, value),
    returnValueForMissingStub: null,
  );

  @override
  set deviceName(String? value) => super.noSuchMethod(
    Invocation.setter(#deviceName, value),
    returnValueForMissingStub: null,
  );

  @override
  set uuid(String? value) => super.noSuchMethod(
    Invocation.setter(#uuid, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> startCommunication() =>
      (super.noSuchMethod(
            Invocation.method(#startCommunication, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> acceptInvite(String? endpointId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptInvite, [endpointId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void rejectInvite() => super.noSuchMethod(
    Invocation.method(#rejectInvite, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> joinCluster(
    String? endpointId,
    String? clusterId,
    String? clusterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#joinCluster, [
              endpointId,
              clusterId,
              clusterName,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> disconnectFromCluster() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromCluster, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stopAll() =>
      (super.noSuchMethod(
            Invocation.method(#stopAll, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  dynamic init(
    _i4.DeviceRepository? deviceRepo,
    _i5.ClusterRepository? clusterRepo,
    _i6.ClusterMemberRepository? clusterMemberRepo,
  ) => super.noSuchMethod(
    Invocation.method(#init, [deviceRepo, clusterRepo, clusterMemberRepo]),
  );

  @override
  void onPayloadReceived(String? endpointId, _i8.Payload? payload) =>
      super.noSuchMethod(
        Invocation.method(#onPayloadReceived, [endpointId, payload]),
        returnValueForMissingStub: null,
      );

  @override
  dynamic sendMessage(
    String? endpointId,
    String? type,
    Map<String, dynamic>? data,
  ) => super.noSuchMethod(
    Invocation.method(#sendMessage, [endpointId, type, data]),
  );

  @override
  void onPayloadUpdate(String? endpointId, _i8.PayloadTransferUpdate? update) =>
      super.noSuchMethod(
        Invocation.method(#onPayloadUpdate, [endpointId, update]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
