// Mocks generated by Mockito 5.4.6 from annotations
// in beacon_project/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:beacon_project/models/profile_model.dart' as _i9;
import 'package:beacon_project/services/db_service.dart' as _i8;
import 'package:beacon_project/services/nearby_connections/nearby_connections.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:nearby_connections/nearby_connections.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NearbyConnectionsBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearbyConnectionsBase extends _i1.Mock
    implements _i3.NearbyConnectionsBase {
  MockNearbyConnectionsBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get deviceName =>
      (super.noSuchMethod(
            Invocation.getter(#deviceName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#deviceName),
            ),
          )
          as String);

  @override
  String get uuid =>
      (super.noSuchMethod(
            Invocation.getter(#uuid),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#uuid)),
          )
          as String);

  @override
  List<String> get connectedEndpoints =>
      (super.noSuchMethod(
            Invocation.getter(#connectedEndpoints),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, String> get activeConnections =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnections),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set deviceName(String? value) => super.noSuchMethod(
    Invocation.setter(#deviceName, value),
    returnValueForMissingStub: null,
  );

  @override
  set uuid(String? value) => super.noSuchMethod(
    Invocation.setter(#uuid, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> requestNearbyPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestNearbyPermissions, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void onPayloadReceived(String? endpointId, _i6.Payload? payload) =>
      super.noSuchMethod(
        Invocation.method(#onPayloadReceived, [endpointId, payload]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> sendMessage(
    String? endpointId,
    String? type,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [endpointId, type, data]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onPayloadUpdate(String? endpointId, _i6.PayloadTransferUpdate? update) =>
      super.noSuchMethod(
        Invocation.method(#onPayloadUpdate, [endpointId, update]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> stopAll() =>
      (super.noSuchMethod(
            Invocation.method(#stopAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> startCommunication() =>
      (super.noSuchMethod(
            Invocation.method(#startCommunication, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DBService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBService extends _i1.Mock implements _i8.DBService {
  MockDBService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i5.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i5.Future<_i2.Database>);

  @override
  _i5.Future<int> insertProfile(_i9.ProfileModel? profile) =>
      (super.noSuchMethod(
            Invocation.method(#insertProfile, [profile]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i9.ProfileModel?> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i5.Future<_i9.ProfileModel?>.value(),
          )
          as _i5.Future<_i9.ProfileModel?>);

  @override
  _i5.Future<int> updateProfile(_i9.ProfileModel? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profile]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteProfile() =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}
