// Mocks generated by Mockito 5.4.6 from annotations
// in beacon_project/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;
import 'dart:ui' as _i15;

import 'package:beacon_project/models/device.dart' as _i16;
import 'package:beacon_project/models/profile_model.dart' as _i9;
import 'package:beacon_project/repositories/cluster_member_repository.dart'
    as _i13;
import 'package:beacon_project/repositories/cluster_repository.dart' as _i12;
import 'package:beacon_project/repositories/device_repository.dart' as _i11;
import 'package:beacon_project/services/db_service.dart' as _i8;
import 'package:beacon_project/services/nearby_connections/nearby_connections.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nearby_connections/nearby_connections.dart' as _i3;
import 'package:nearby_connections/src/classes.dart' as _i14;
import 'package:nearby_connections/src/defs.dart' as _i5;
import 'package:shared_preferences/shared_preferences.dart' as _i7;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Nearby].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearby extends _i1.Mock implements _i3.Nearby {
  MockNearby() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> copyFileAndDeleteOriginal(
    String? sourceUri,
    String? destinationFilepath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyFileAndDeleteOriginal, [
              sourceUri,
              destinationFilepath,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> startAdvertising(
    String? userNickName,
    _i5.Strategy? strategy, {
    required _i5.OnConnectionInitiated? onConnectionInitiated,
    required _i5.OnConnectionResult? onConnectionResult,
    required _i5.OnDisconnected? onDisconnected,
    String? serviceId = 'com.pkmnapps.nearby_connections',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startAdvertising,
              [userNickName, strategy],
              {
                #onConnectionInitiated: onConnectionInitiated,
                #onConnectionResult: onConnectionResult,
                #onDisconnected: onDisconnected,
                #serviceId: serviceId,
              },
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> startDiscovery(
    String? userNickName,
    _i5.Strategy? strategy, {
    required _i5.OnEndpointFound? onEndpointFound,
    required _i5.OnEndpointLost? onEndpointLost,
    String? serviceId = 'com.pkmnapps.nearby_connections',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startDiscovery,
              [userNickName, strategy],
              {
                #onEndpointFound: onEndpointFound,
                #onEndpointLost: onEndpointLost,
                #serviceId: serviceId,
              },
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopAllEndpoints() =>
      (super.noSuchMethod(
            Invocation.method(#stopAllEndpoints, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnectFromEndpoint(String? endpointId) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromEndpoint, [endpointId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> requestConnection(
    String? userNickName,
    String? endpointId, {
    required _i5.OnConnectionInitiated? onConnectionInitiated,
    required _i5.OnConnectionResult? onConnectionResult,
    required _i5.OnDisconnected? onDisconnected,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestConnection,
              [userNickName, endpointId],
              {
                #onConnectionInitiated: onConnectionInitiated,
                #onConnectionResult: onConnectionResult,
                #onDisconnected: onDisconnected,
              },
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> acceptConnection(
    String? endpointId, {
    required _i5.OnPayloadReceived? onPayLoadRecieved,
    _i5.OnPayloadTransferUpdate? onPayloadTransferUpdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #acceptConnection,
              [endpointId],
              {
                #onPayLoadRecieved: onPayLoadRecieved,
                #onPayloadTransferUpdate: onPayloadTransferUpdate,
              },
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> rejectConnection(String? endpointId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectConnection, [endpointId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> sendBytesPayload(String? endpointId, _i6.Uint8List? bytes) =>
      (super.noSuchMethod(
            Invocation.method(#sendBytesPayload, [endpointId, bytes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> sendFilePayload(String? endpointId, String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#sendFilePayload, [endpointId, filePath]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> cancelPayload(int? payloadId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelPayload, [payloadId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i7.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i4.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DBService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBService extends _i1.Mock implements _i8.DBService {
  MockDBService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> insertProfile(_i9.ProfileModel? profile) =>
      (super.noSuchMethod(
            Invocation.method(#insertProfile, [profile]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i9.ProfileModel?> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i4.Future<_i9.ProfileModel?>.value(),
          )
          as _i4.Future<_i9.ProfileModel?>);

  @override
  _i4.Future<int> updateProfile(_i9.ProfileModel? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profile]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteProfile() =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [NearbyConnectionsBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearbyConnectionsBase extends _i1.Mock
    implements _i10.NearbyConnectionsBase {
  MockNearbyConnectionsBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get connectedEndpoints =>
      (super.noSuchMethod(
            Invocation.getter(#connectedEndpoints),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, String> get activeConnections =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnections),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set deviceRepository(_i11.DeviceRepository? value) => super.noSuchMethod(
    Invocation.setter(#deviceRepository, value),
    returnValueForMissingStub: null,
  );

  @override
  set clusterRepository(_i12.ClusterRepository? value) => super.noSuchMethod(
    Invocation.setter(#clusterRepository, value),
    returnValueForMissingStub: null,
  );

  @override
  set clusterMemberRepository(_i13.ClusterMemberRepository? value) =>
      super.noSuchMethod(
        Invocation.setter(#clusterMemberRepository, value),
        returnValueForMissingStub: null,
      );

  @override
  set deviceName(String? value) => super.noSuchMethod(
    Invocation.setter(#deviceName, value),
    returnValueForMissingStub: null,
  );

  @override
  set uuid(String? value) => super.noSuchMethod(
    Invocation.setter(#uuid, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> init(
    _i11.DeviceRepository? deviceRepo,
    _i12.ClusterRepository? clusterRepo,
    _i13.ClusterMemberRepository? clusterMemberRepo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#init, [
              deviceRepo,
              clusterRepo,
              clusterMemberRepo,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> requestNearbyPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestNearbyPermissions, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void onPayloadReceived(String? endpointId, _i14.Payload? payload) =>
      super.noSuchMethod(
        Invocation.method(#onPayloadReceived, [endpointId, payload]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> sendMessage(
    String? endpointId,
    String? type,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [endpointId, type, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onPayloadUpdate(
    String? endpointId,
    _i14.PayloadTransferUpdate? update,
  ) => super.noSuchMethod(
    Invocation.method(#onPayloadUpdate, [endpointId, update]),
    returnValueForMissingStub: null,
  );

  @override
  void resetState() => super.noSuchMethod(
    Invocation.method(#resetState, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> stopAll() =>
      (super.noSuchMethod(
            Invocation.method(#stopAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> startCommunication() =>
      (super.noSuchMethod(
            Invocation.method(#startCommunication, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NearbyConnectionsInitiator].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearbyConnectionsInitiator extends _i1.Mock
    implements _i10.NearbyConnectionsInitiator {
  MockNearbyConnectionsInitiator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i16.Device> get availableDevices =>
      (super.noSuchMethod(
            Invocation.getter(#availableDevices),
            returnValue: <_i16.Device>[],
          )
          as List<_i16.Device>);

  @override
  List<String> get connectedEndpoints =>
      (super.noSuchMethod(
            Invocation.getter(#connectedEndpoints),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, String> get activeConnections =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnections),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set deviceRepository(_i11.DeviceRepository? value) => super.noSuchMethod(
    Invocation.setter(#deviceRepository, value),
    returnValueForMissingStub: null,
  );

  @override
  set clusterRepository(_i12.ClusterRepository? value) => super.noSuchMethod(
    Invocation.setter(#clusterRepository, value),
    returnValueForMissingStub: null,
  );

  @override
  set clusterMemberRepository(_i13.ClusterMemberRepository? value) =>
      super.noSuchMethod(
        Invocation.setter(#clusterMemberRepository, value),
        returnValueForMissingStub: null,
      );

  @override
  set deviceName(String? value) => super.noSuchMethod(
    Invocation.setter(#deviceName, value),
    returnValueForMissingStub: null,
  );

  @override
  set uuid(String? value) => super.noSuchMethod(
    Invocation.setter(#uuid, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> startCommunication() =>
      (super.noSuchMethod(
            Invocation.method(#startCommunication, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> inviteToCluster(String? endpointId, String? clusterId) =>
      (super.noSuchMethod(
            Invocation.method(#inviteToCluster, [endpointId, clusterId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> transferOwnershipBeforeDisconnect() =>
      (super.noSuchMethod(
            Invocation.method(#transferOwnershipBeforeDisconnect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopAll() =>
      (super.noSuchMethod(
            Invocation.method(#stopAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> init(
    _i11.DeviceRepository? deviceRepo,
    _i12.ClusterRepository? clusterRepo,
    _i13.ClusterMemberRepository? clusterMemberRepo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#init, [
              deviceRepo,
              clusterRepo,
              clusterMemberRepo,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> requestNearbyPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestNearbyPermissions, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void onPayloadReceived(String? endpointId, _i14.Payload? payload) =>
      super.noSuchMethod(
        Invocation.method(#onPayloadReceived, [endpointId, payload]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> sendMessage(
    String? endpointId,
    String? type,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [endpointId, type, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onPayloadUpdate(
    String? endpointId,
    _i14.PayloadTransferUpdate? update,
  ) => super.noSuchMethod(
    Invocation.method(#onPayloadUpdate, [endpointId, update]),
    returnValueForMissingStub: null,
  );

  @override
  void resetState() => super.noSuchMethod(
    Invocation.method(#resetState, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NearbyConnectionsJoiner].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearbyConnectionsJoiner extends _i1.Mock
    implements _i10.NearbyConnectionsJoiner {
  MockNearbyConnectionsJoiner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> get discoveredClusters =>
      (super.noSuchMethod(
            Invocation.getter(#discoveredClusters),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  List<String> get connectedEndpoints =>
      (super.noSuchMethod(
            Invocation.getter(#connectedEndpoints),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, String> get activeConnections =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnections),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set deviceRepository(_i11.DeviceRepository? value) => super.noSuchMethod(
    Invocation.setter(#deviceRepository, value),
    returnValueForMissingStub: null,
  );

  @override
  set clusterRepository(_i12.ClusterRepository? value) => super.noSuchMethod(
    Invocation.setter(#clusterRepository, value),
    returnValueForMissingStub: null,
  );

  @override
  set clusterMemberRepository(_i13.ClusterMemberRepository? value) =>
      super.noSuchMethod(
        Invocation.setter(#clusterMemberRepository, value),
        returnValueForMissingStub: null,
      );

  @override
  set deviceName(String? value) => super.noSuchMethod(
    Invocation.setter(#deviceName, value),
    returnValueForMissingStub: null,
  );

  @override
  set uuid(String? value) => super.noSuchMethod(
    Invocation.setter(#uuid, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> startCommunication() =>
      (super.noSuchMethod(
            Invocation.method(#startCommunication, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> acceptInvite(String? endpointId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptInvite, [endpointId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void rejectInvite() => super.noSuchMethod(
    Invocation.method(#rejectInvite, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> joinCluster(
    String? endpointId,
    String? clusterId,
    String? clusterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#joinCluster, [
              endpointId,
              clusterId,
              clusterName,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnectFromCluster() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromCluster, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopAll() =>
      (super.noSuchMethod(
            Invocation.method(#stopAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> init(
    _i11.DeviceRepository? deviceRepo,
    _i12.ClusterRepository? clusterRepo,
    _i13.ClusterMemberRepository? clusterMemberRepo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#init, [
              deviceRepo,
              clusterRepo,
              clusterMemberRepo,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> requestNearbyPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestNearbyPermissions, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void onPayloadReceived(String? endpointId, _i14.Payload? payload) =>
      super.noSuchMethod(
        Invocation.method(#onPayloadReceived, [endpointId, payload]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> sendMessage(
    String? endpointId,
    String? type,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [endpointId, type, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onPayloadUpdate(
    String? endpointId,
    _i14.PayloadTransferUpdate? update,
  ) => super.noSuchMethod(
    Invocation.method(#onPayloadUpdate, [endpointId, update]),
    returnValueForMissingStub: null,
  );

  @override
  void resetState() => super.noSuchMethod(
    Invocation.method(#resetState, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
