// Mocks generated by Mockito 5.4.6 from annotations
// in beacon_project/test/nearby_connections_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nearby_connections/src/defs.dart' as _i4;
import 'package:nearby_connections/src/nearby.dart' as _i2;
import 'package:shared_preferences/src/shared_preferences_legacy.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [Nearby].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearby extends _i1.Mock implements _i2.Nearby {
  MockNearby() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> copyFileAndDeleteOriginal(
    String? sourceUri,
    String? destinationFilepath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyFileAndDeleteOriginal, [
              sourceUri,
              destinationFilepath,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> startAdvertising(
    String? userNickName,
    _i4.Strategy? strategy, {
    required _i4.OnConnectionInitiated? onConnectionInitiated,
    required _i4.OnConnectionResult? onConnectionResult,
    required _i4.OnDisconnected? onDisconnected,
    String? serviceId = 'com.pkmnapps.nearby_connections',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startAdvertising,
              [userNickName, strategy],
              {
                #onConnectionInitiated: onConnectionInitiated,
                #onConnectionResult: onConnectionResult,
                #onDisconnected: onDisconnected,
                #serviceId: serviceId,
              },
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> startDiscovery(
    String? userNickName,
    _i4.Strategy? strategy, {
    required _i4.OnEndpointFound? onEndpointFound,
    required _i4.OnEndpointLost? onEndpointLost,
    String? serviceId = 'com.pkmnapps.nearby_connections',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startDiscovery,
              [userNickName, strategy],
              {
                #onEndpointFound: onEndpointFound,
                #onEndpointLost: onEndpointLost,
                #serviceId: serviceId,
              },
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopAllEndpoints() =>
      (super.noSuchMethod(
            Invocation.method(#stopAllEndpoints, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnectFromEndpoint(String? endpointId) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromEndpoint, [endpointId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> requestConnection(
    String? userNickName,
    String? endpointId, {
    required _i4.OnConnectionInitiated? onConnectionInitiated,
    required _i4.OnConnectionResult? onConnectionResult,
    required _i4.OnDisconnected? onDisconnected,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestConnection,
              [userNickName, endpointId],
              {
                #onConnectionInitiated: onConnectionInitiated,
                #onConnectionResult: onConnectionResult,
                #onDisconnected: onDisconnected,
              },
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> acceptConnection(
    String? endpointId, {
    required _i4.OnPayloadReceived? onPayLoadRecieved,
    _i4.OnPayloadTransferUpdate? onPayloadTransferUpdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #acceptConnection,
              [endpointId],
              {
                #onPayLoadRecieved: onPayLoadRecieved,
                #onPayloadTransferUpdate: onPayloadTransferUpdate,
              },
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> rejectConnection(String? endpointId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectConnection, [endpointId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> sendBytesPayload(String? endpointId, _i5.Uint8List? bytes) =>
      (super.noSuchMethod(
            Invocation.method(#sendBytesPayload, [endpointId, bytes]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> sendFilePayload(String? endpointId, String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#sendFilePayload, [endpointId, filePath]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> cancelPayload(int? payloadId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelPayload, [payloadId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i6.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i3.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
